// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using users.Models;

namespace users.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20191209105939_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("users.Models.User", b =>
                {
                    b.Property<int>("u_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("U_Active")
                        .HasColumnType("bit");

                    b.Property<string>("U_Code")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<int>("u_DefaultLanguage")
                        .HasColumnType("int");

                    b.Property<string>("u_ForeignCode")
                        .HasColumnType("varchar(60)");

                    b.Property<int>("u_ForeignId")
                        .HasColumnType("int");

                    b.Property<int>("u_MachineID")
                        .HasColumnType("int");

                    b.Property<string>("u_Name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("u_Pwd")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<int>("u_Type")
                        .HasColumnType("int");

                    b.HasKey("u_Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
